# Generated by Django 3.2.25 on 2026-01-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='home/')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura_seg_sex', models.TimeField()),
                ('fechamento_seg_sex', models.TimeField()),
                ('abertura_sab', models.TimeField()),
                ('fechamento_sab', models.TimeField()),
                ('abertura_dom', models.TimeField()),
                ('fechamento_dom', models.TimeField()),
                ('abertura_feriado', models.TimeField(blank=True, null=True)),
                ('fechamento_feriado', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PratoDestaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.ImageField(blank=True, upload_to='pratos/')),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='info/')),
            ],
        ),
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.ImageField(blank=True, upload_to='pratos/')),
                ('ativo', models.BooleanField(default=True)),
                ('vegetariano', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos', to='loja.categoriaprato')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_1', models.TextField(blank=True)),
                ('texto_2', models.TextField(blank=True)),
                ('texto_3', models.TextField(blank=True)),
                ('imagem_1', models.ImageField(blank=True, upload_to='home/')),
                ('texto_img_1', models.CharField(blank=True, max_length=150)),
                ('imagem_2', models.ImageField(blank=True, upload_to='home/')),
                ('texto_img_2', models.CharField(blank=True, max_length=150)),
                ('imagem_3', models.ImageField(blank=True, upload_to='home/')),
                ('texto_img_3', models.CharField(blank=True, max_length=150)),
                ('imagem_4', models.ImageField(blank=True, upload_to='home/')),
                ('texto_img_4', models.CharField(blank=True, max_length=150)),
                ('imagem_5', models.ImageField(blank=True, upload_to='home/')),
                ('texto_img_5', models.CharField(blank=True, max_length=150)),
                ('ordem', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='loja.homecategoria')),
            ],
        ),
    ]
