# Generated by Django 3.2.25 on 2026-01-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Promoção')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Regras')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='promocoes/', verbose_name='Imagem da Oferta')),
                ('tag_desconto', models.CharField(blank=True, max_length=20, verbose_name='Etiqueta (ex: 20% OFF)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Ativa?')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['ordem'],
            },
        ),
    ]
