# Generated by Django 3.2.25 on 2026-01-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebloco',
            name='titulo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
