# Generated by Django 3.2.25 on 2026-01-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_homebloco_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebloco',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
