# Generated by Django 3.2.25 on 2026-01-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_homebloco_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='texto_link',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
