# Generated by Django 3.2.25 on 2026-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20260122_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='insta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
