# Generated by Django 3.2.25 on 2026-01-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_auto_20260122_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebloco',
            name='link1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='link1_texto',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='link2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='link2_texto',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='link3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='link3_texto',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
