# Generated by Django 3.2.25 on 2026-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_auto_20260122_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebloco',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, verbose_name=' *Título* Pode ficar vazio'),
        ),
    ]
