# Generated by Django 3.2.25 on 2026-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_alter_homebloco_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebloco',
            name='botao1_link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='botao2_link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='botao3_link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='botoao1_texo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='botoao2_texo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homebloco',
            name='botoao3_texo',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
