# Generated by Django 3.2.25 on 2026-01-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_auto_20260122_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homebloco',
            old_name='botoao1_texo',
            new_name='botao1_texto',
        ),
        migrations.RenameField(
            model_name='homebloco',
            old_name='botoao2_texo',
            new_name='botao2_texto',
        ),
        migrations.RenameField(
            model_name='homebloco',
            old_name='botoao3_texo',
            new_name='botao3_texto',
        ),
    ]
