# Generated by Django 3.2.25 on 2026-01-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_auto_20260122_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SobreBloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('texto', models.TextField(blank=True)),
                ('imagem_1', models.ImageField(blank=True, upload_to='sobre/')),
                ('texto_img_1', models.CharField(blank=True, max_length=150)),
                ('imagem_2', models.ImageField(blank=True, upload_to='sobre/')),
                ('texto_img_2', models.CharField(blank=True, max_length=150)),
                ('imagem_3', models.ImageField(blank=True, upload_to='sobre/')),
                ('texto_img_3', models.CharField(blank=True, max_length=150)),
                ('botao_link', models.URLField(blank=True, help_text='Link do botão (ex: https://site.com)')),
                ('botao_texto', models.CharField(blank=True, help_text='Texto que aparece no botão', max_length=100)),
                ('link', models.URLField(blank=True, help_text='Link  (ex: https://site.com)')),
                ('link_texto', models.CharField(blank=True, help_text='Texto que substitui o link', max_length=150)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='loja.sobrecategoria')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
