# Generated by Django 3.2.25 on 2026-01-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_sobrebloco_sobrecategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobrebloco',
            old_name='botao_link',
            new_name='botao1_link',
        ),
        migrations.RenameField(
            model_name='sobrebloco',
            old_name='botao_texto',
            new_name='botao1_texto',
        ),
        migrations.RenameField(
            model_name='sobrebloco',
            old_name='link',
            new_name='link1',
        ),
        migrations.RenameField(
            model_name='sobrebloco',
            old_name='link_texto',
            new_name='link1_texto',
        ),
        migrations.RenameField(
            model_name='sobrebloco',
            old_name='texto',
            new_name='texto1',
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='botao2_link',
            field=models.URLField(blank=True, help_text='Link do botão (ex: https://site.com)'),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='botao2_texto',
            field=models.CharField(blank=True, help_text='Texto que aparece no botão', max_length=100),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='botao3_link',
            field=models.URLField(blank=True, help_text='Link do botão (ex: https://site.com)'),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='botao3_texto',
            field=models.CharField(blank=True, help_text='Texto que aparece no botão', max_length=100),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='link2',
            field=models.URLField(blank=True, help_text='Link  (ex: https://site.com)'),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='link2_texto',
            field=models.CharField(blank=True, help_text='Texto que substitui o link', max_length=150),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='link3',
            field=models.URLField(blank=True, help_text='Link  (ex: https://site.com)'),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='link3_texto',
            field=models.CharField(blank=True, help_text='Texto que substitui o link', max_length=150),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='texto2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='texto3',
            field=models.TextField(blank=True),
        ),
    ]
