# Generated by Django 3.2.25 on 2026-01-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_auto_20260122_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterField(
            model_name='categoriaprato',
            name='nome',
            field=models.CharField(help_text='Nome da categoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contato', max_length=254),
        ),
        migrations.AlterField(
            model_name='contato',
            name='insta',
            field=models.CharField(blank=True, help_text='Instagram (@usuario)', max_length=100),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone principal', max_length=20),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone2',
            field=models.CharField(blank=True, help_text='Telefone secundário', max_length=20),
        ),
        migrations.AlterField(
            model_name='contato',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número do WhatsApp', max_length=20),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Marque para exibir no site'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do banner', upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='link',
            field=models.CharField(blank=True, help_text='Link do banner', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='texto',
            field=models.TextField(blank=True, help_text='Texto complementar do banner'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='texto_link',
            field=models.CharField(blank=True, help_text='Texto do botão/link do banner', max_length=35),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='titulo',
            field=models.CharField(help_text='Título principal do banner', max_length=100),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='botao1_link',
            field=models.CharField(blank=True, help_text='Link do botão 1', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='botao1_texto',
            field=models.CharField(blank=True, help_text='Texto do botão 1', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='botao2_link',
            field=models.CharField(blank=True, help_text='Link do botão 2', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='botao2_texto',
            field=models.CharField(blank=True, help_text='Texto do botão 2', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='botao3_link',
            field=models.CharField(blank=True, help_text='Link do botão 3', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='botao3_texto',
            field=models.CharField(blank=True, help_text='Texto do botão 3', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='imagem_1',
            field=models.ImageField(blank=True, help_text='Imagem 1', upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='imagem_2',
            field=models.ImageField(blank=True, help_text='Imagem 2', upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='imagem_3',
            field=models.ImageField(blank=True, help_text='Imagem 3', upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='imagem_4',
            field=models.ImageField(blank=True, help_text='Imagem 4', upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='imagem_5',
            field=models.ImageField(blank=True, help_text='Imagem 5', upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='link1',
            field=models.CharField(blank=True, help_text='Link 1', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='link1_texto',
            field=models.CharField(blank=True, help_text='Texto do link 1', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='link2',
            field=models.CharField(blank=True, help_text='Link 2', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='link2_texto',
            field=models.CharField(blank=True, help_text='Texto do link 2', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='link3',
            field=models.CharField(blank=True, help_text='Link 3', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='link3_texto',
            field=models.CharField(blank=True, help_text='Texto do link 3', max_length=250),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem do bloco'),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='texto_1',
            field=models.TextField(blank=True, help_text='Texto 1 do bloco'),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='texto_2',
            field=models.TextField(blank=True, help_text='Texto 2 do bloco'),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='texto_3',
            field=models.TextField(blank=True, help_text='Texto 3 do bloco'),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='texto_img_1',
            field=models.CharField(blank=True, help_text='Texto da imagem 1', max_length=150),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='texto_img_2',
            field=models.CharField(blank=True, help_text='Texto da imagem 2', max_length=150),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='texto_img_3',
            field=models.CharField(blank=True, help_text='Texto da imagem 3', max_length=150),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='texto_img_4',
            field=models.CharField(blank=True, help_text='Texto da imagem 4', max_length=150),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='texto_img_5',
            field=models.CharField(blank=True, help_text='Texto da imagem 5', max_length=150),
        ),
        migrations.AlterField(
            model_name='homebloco',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título opcional do bloco', max_length=150),
        ),
        migrations.AlterField(
            model_name='homecategoria',
            name='nome',
            field=models.CharField(help_text='Nome da categoria da home', max_length=100),
        ),
        migrations.AlterField(
            model_name='homecategoria',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='abertura_dom',
            field=models.TimeField(help_text='Abertura Domingo'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='abertura_feriado',
            field=models.TimeField(blank=True, help_text='Abertura Feriado', null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='abertura_sab',
            field=models.TimeField(help_text='Abertura Sábado'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='abertura_seg_sex',
            field=models.TimeField(help_text='Abertura (Seg–Sex)'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fechamento_dom',
            field=models.TimeField(help_text='Fechamento Domingo'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fechamento_feriado',
            field=models.TimeField(blank=True, help_text='Fechamento Feriado', null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fechamento_sab',
            field=models.TimeField(help_text='Fechamento Sábado'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fechamento_seg_sex',
            field=models.TimeField(help_text='Fechamento (Seg–Sex)'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Disponível no cardápio'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição do prato'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do prato', upload_to='pratos/'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='nome',
            field=models.CharField(help_text='Nome do prato', max_length=100),
        ),
        migrations.AlterField(
            model_name='prato',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço', max_digits=8),
        ),
        migrations.AlterField(
            model_name='prato',
            name='vegetariano',
            field=models.BooleanField(default=False, help_text='Prato vegetariano'),
        ),
        migrations.AlterField(
            model_name='pratodestaque',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição'),
        ),
        migrations.AlterField(
            model_name='pratodestaque',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem', upload_to='pratos/'),
        ),
        migrations.AlterField(
            model_name='pratodestaque',
            name='nome',
            field=models.CharField(help_text='Nome do prato em destaque', max_length=100),
        ),
        migrations.AlterField(
            model_name='pratodestaque',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='pratodestaque',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço', max_digits=8),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Promoção ativa'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição ou regras'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem da promoção', null=True, upload_to='promocoes/'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='tag_desconto',
            field=models.CharField(blank=True, help_text='Ex: 20% OFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='titulo',
            field=models.CharField(help_text='Título da promoção', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(help_text='Logotipo do restaurante', upload_to='info/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='nome',
            field=models.CharField(help_text='Nome do restaurante ou site', max_length=150),
        ),
        migrations.AlterField(
            model_name='slogan',
            name='slogan',
            field=models.CharField(help_text='Frase curta de impacto exibida no site', max_length=350),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Bloco ativo'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='botao1_link',
            field=models.URLField(blank=True, help_text='Link do botão 1'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='botao1_texto',
            field=models.CharField(blank=True, help_text='Texto do botão 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='botao2_link',
            field=models.URLField(blank=True, help_text='Link do botão 2'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='botao2_texto',
            field=models.CharField(blank=True, help_text='Texto do botão 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='botao3_link',
            field=models.URLField(blank=True, help_text='Link do botão 3'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='botao3_texto',
            field=models.CharField(blank=True, help_text='Texto do botão 3', max_length=100),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='imagem_1',
            field=models.ImageField(blank=True, help_text='Imagem 1', upload_to='sobre/'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='imagem_2',
            field=models.ImageField(blank=True, help_text='Imagem 2', upload_to='sobre/'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='imagem_3',
            field=models.ImageField(blank=True, help_text='Imagem 3', upload_to='sobre/'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='link1',
            field=models.URLField(blank=True, help_text='Link 1'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='link1_texto',
            field=models.CharField(blank=True, help_text='Texto do link 1', max_length=150),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='link2',
            field=models.URLField(blank=True, help_text='Link 2'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='link2_texto',
            field=models.CharField(blank=True, help_text='Texto do link 2', max_length=150),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='link3',
            field=models.URLField(blank=True, help_text='Link 3'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='link3_texto',
            field=models.CharField(blank=True, help_text='Texto do link 3', max_length=150),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem do bloco'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='texto1',
            field=models.TextField(blank=True, help_text='Texto 1'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='texto2',
            field=models.TextField(blank=True, help_text='Texto 2'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='texto3',
            field=models.TextField(blank=True, help_text='Texto 3'),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='texto_img_1',
            field=models.CharField(blank=True, help_text='Texto da imagem 1', max_length=150),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='texto_img_2',
            field=models.CharField(blank=True, help_text='Texto da imagem 2', max_length=150),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='texto_img_3',
            field=models.CharField(blank=True, help_text='Texto da imagem 3', max_length=150),
        ),
        migrations.AlterField(
            model_name='sobrebloco',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título opcional', max_length=150),
        ),
        migrations.AlterField(
            model_name='sobrecategoria',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Ativo'),
        ),
        migrations.AlterField(
            model_name='sobrecategoria',
            name='nome',
            field=models.CharField(help_text='Nome da categoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='sobrecategoria',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem'),
        ),
    ]
