# Generated by Django 3.2.25 on 2026-01-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_remove_prato_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição'),
        ),
    ]
