# Generated by Django 3.2.25 on 2026-01-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_prato_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebloco',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome do bloco', max_length=100),
        ),
        migrations.AddField(
            model_name='sobrebloco',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome do bloco', max_length=100),
        ),
    ]
