# Generated by Django 3.2.25 on 2026-01-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_auto_20260123_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebloco',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Bloco ativo'),
        ),
        migrations.AddField(
            model_name='homecategoria',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Bloco ativo'),
        ),
    ]
