# Generated by Django 3.2.25 on 2026-01-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_auto_20260123_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprato',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Categoria ativa'),
        ),
    ]
