# Generated by Django 3.2.25 on 2026-01-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0020_auto_20260123_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da galeria', max_length=150)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='BlocoGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem da galeria', upload_to='galeria/')),
                ('legenda', models.CharField(blank=True, help_text='Legenda da imagem', max_length=150)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem do bloco')),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='loja.galeriacategoria')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
