# Generated by Django 3.2.25 on 2026-01-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0021_blocogaleria_galeriacategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocogaleria',
            name='imagem_texto',
            field=models.CharField(blank=True, help_text='Legenda da imagem', max_length=150),
        ),
    ]
