# Generated by Django 3.2.25 on 2026-01-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0022_blocogaleria_imagem_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocogaleria',
            name='nome',
            field=models.CharField(blank=True, help_text='nome apenas para identificação', max_length=150),
        ),
    ]
